In [13]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
from sklearn.svm import SVC
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
data= pd.read_csv('glass SVM.csv')
y=data.Type
x=data.drop('Type',axis=1)
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.3)

model1 = SVC(kernel='linear')
model1.fit(xtrain,ytrain)
y_pred=model1.predict(xtest)
print(accuracy_score(y_pred,ytest))
print(confusion_matrix(y_pred,ytest))
print(classification_report(y_pred,ytest))
print('\n')

model2 = SVC(kernel='poly')
model2.fit(xtrain,ytrain)
y_pred1=model2.predict(xtest)
print(accuracy_score(y_pred1,ytest))
print(confusion_matrix(y_pred1,ytest))
print(classification_report(y_pred1,ytest))
print('\n')

model3 = SVC(kernel='sigmoid')
model3.fit(xtrain,ytrain)
y_pred2=model3.predict(xtest)
print(accuracy_score(y_pred2,ytest))
print(confusion_matrix(y_pred2,ytest))
print(classification_report(y_pred2,ytest))
print('\n')

model4 = SVC(kernel='rbf')
model4.fit(xtrain,ytrain)
y_pred3=model4.predict(xtest)
print(accuracy_score(y_pred3,ytest))
print(confusion_matrix(y_pred3,ytest))
print(classification_report(y_pred3,ytest))

1.0
[[22  0  0  0  0  0]
 [ 0 22  0  0  0  0]
 [ 0  0  5  0  0  0]
 [ 0  0  0  5  0  0]
 [ 0  0  0  0  4  0]
 [ 0  0  0  0  0  7]]
              precision    recall  f1-score   support

           1       1.00      1.00      1.00        22
           2       1.00      1.00      1.00        22
           3       1.00      1.00      1.00         5
           5       1.00      1.00      1.00         5
           6       1.00      1.00      1.00         4
           7       1.00      1.00      1.00         7

    accuracy                           1.00        65
   macro avg       1.00      1.00      1.00        65
weighted avg       1.00      1.00      1.00        65



0.9692307692307692
[[22  0  0  0  0  0]
 [ 0 22  0  0  0  0]
 [ 0  0  5  0  0  0]
 [ 0  0  0  5  2  0]
 [ 0  0  0  0  2  0]
 [ 0  0  0  0  0  7]]
              precision    recall  f1-score   support

           1       1.00      1.00      1.00        22
           2       1.00      1.00      1.00        22
           3   

C:\Users\Navneeth\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Navneeth\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Navneeth\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Navneeth\anaconda3\lib\site-packages\sklearn\metrics\_classif

In [14]:
x

Id       RI     Na    Mg    Al    Si      K    Ca    Ba   Fe
0      1  1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.00  0.0
1      2  1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.00  0.0
2      3  1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.00  0.0
3      4  1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.00  0.0
4      5  1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.00  0.0
..   ...      ...    ...   ...   ...    ...   ...   ...   ...  ...
209  210  1.51623  14.14  0.00  2.88  72.61  0.08  9.18  1.06  0.0
210  211  1.51685  14.92  0.00  1.99  73.06  0.00  8.40  1.59  0.0
211  212  1.52065  14.36  0.00  2.02  73.42  0.00  8.44  1.64  0.0
212  213  1.51651  14.38  0.00  1.94  73.61  0.00  8.48  1.57  0.0
213  214  1.51711  14.23  0.00  2.08  73.36  0.00  8.62  1.67  0.0

[214 rows x 10 columns]

In [15]:
y

0      1
1      1
2      1
3      1
4      1
      ..
209    7
210    7
211    7
212    7
213    7
Name: Type, Length: 214, dtype: int64